
name: SQL Repository

on:
  push:
    branches: [ github_actions_tests_fix ]

jobs:

  tests:
    name: Check Githubactions tests setup
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 7s
          --health-timeout 3s
          --health-retries 5

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov coveralls

    - name: Run tests with coverage
      env:
        POSTGRES_URL: "postgresql://postgres:postgres@localhost:5432"
        ASYNC_POSTGRES_URL: "postgresql+asyncpg://postgres:postgres@localhost:5432"
      run: |
        python -m pytest tests --cov=./ --cov-report=xml -p pytest_asyncio

    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls
