
name: SQL Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 7s
          --health-timeout 3s
          --health-retries 5

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Install Requirements
      run: python -m pip install -r requirements.txt

    - name: Run tests
      env:
        POSTGRES_URL: "postgresql://postgres:postgres@localhost:5432/test_db"
      run: python -m pytest
